export const SITES_LIST_FETCH = 'unifi.SITES_LIST_FETCH'
export const PROGRAMMES_LIST_FETCH = 'unifi.PROGRAMMES_LIST_FETCH'
export const HOLDERS_LIST_FETCH = 'unifi.HOLDERS_LIST_FETCH'
export const HOLDER_GET_FETCH = 'unifi.HOLDER_GET_FETCH'
