= unifi.id Platform

== Useful links

- link:doc/api-spec.adoc[API Specification]

== Build dependencies

- Oracle JDK 9
- Maven 3.5+
- PostgreSQL 9.6+ with a `unifi` database, see below
- RabbitMQ (runtime only)

Preferably, just set up a VM as described below.

== Development VM setup

Install https://www.virtualbox.org/wiki/Downloads[VirtualBox] and
https://www.vagrantup.com/downloads.html[Vagrant] for your host OS.

Then run:

----
vagrant up
vagrant ssh
cd unifi.id/unifi-service
mvn clean install

mvn exec:java -pl unifi-core
----

Then connect to the server via the following URLs:

* For MessagePack: ws://<vm ip>:8000/service/msgpack
* For JSON: ws://<vm ip>:8000/service/json

You can find the VM IP by SSHing in, and running `ip addr`.

If the SQL schema has changed and migration fails you can recreate the database
as follows: `dropdb unifi && createdb unifi`

To start again from a clean slate run `vagrant destroy`.

Other useful commands on the VM:

----
psql -d unifi
----

=== Schema generation

The `unifi-core-schema` module requires a local postgres instance with a
database named `unifi` in order to generate a jOOQ schema. This step can be
skipped with `mvn -pl '!unifi-core-schema' ...` if `unifi-core-schema` is
already installed.
