= unifi.id Platform

== Useful links

- link:doc/api-spec.adoc[API Specification]
- link:doc/access-control.adoc[Access Control]
- link:doc/min-requirements.adoc[Minimum Requirements]

== Build dependencies

- Oracle JDK 10
- Maven 3.5+
- PostgreSQL 9.6+ with a `unifi` database, see below
- RabbitMQ (runtime only)

Preferably, just set up a VM as described below.

== Development VM setup

Install https://www.virtualbox.org/wiki/Downloads[VirtualBox] and
https://www.vagrantup.com/downloads.html[Vagrant] for your host OS.

Then run:

----
vagrant up
vagrant ssh
cd unifi.id/unifi-service
mvn clean install

mvn exec:java -pl unifi-core
----

Then connect to the server via the following URLs:

* For MessagePack: ws://<vm ip>:8000/service/msgpack
* For JSON: ws://<vm ip>:8000/service/json

You can find the VM IP by SSHing in, and running `ip addr`.

If the SQL schema has changed and migration fails you can recreate the database
as follows: `dropdb unifi && createdb unifi`

To start again from a clean slate run `vagrant destroy`.

Other useful commands on the VM:

----
psql -d unifi
# Once inside set default schemata using: set search_path to attendance, core, public;
# Set the session time zone: set session timezone to 'utc';

# Quickly recreate and migrate service database
dropdb --if-exists unifi && createdb unifi && mvn flyway:migrate -pl unifi-core-schema,unifi-attendance-schema

# Start mock agent (readers must exist in the core DB)
mvn exec:java -pl unifi-mock-agent -Dunifi.client.id=test-club

# Use JSON API from command line
ws ws://<vm ip>:8000/service/json # using https://github.com/hashrocket/ws
----

On the Build Node/CI Server (or a server with the debian build tools installed:

`apt-get install build-essential fakeroot devscripts`

We can build the debian packages ready for deployment:

----
vagrant up
vagrant ssh
cd unifi.id/unifi-service
mvn clean install

mvn exec:java -pl unifi-core

./build-deb.sh unifi-core 1.0.2 unifi-core/target/unifi-core-0.1-SNAPSHOT-jar-with-dependencies.jar
./build-deb.sh unifi-core-agent 1.0.2 unifi-core-agent/target/unifi-core-agent-0.1-SNAPSHOT-jar-with-dependencies.jar

# Produces unifi-core-1.0.2.deb and unifi-core-agent-1.0.2.deb, ready for install
dpkg -i unifi-core-1.0.2.deb
----

=== IntelliJ IDEA settings

The project requires parameter names to be present in the Java bytecode for
correct JSON deserialization, which needs to be configured in IntelliJ IDEA.
Go to
`Project Structure > Build, Execution, Deployment > Compiler > Java Compiler`
and put `-parameters` in `Additional command line parameters`.

=== Schema generation

The `unifi-*-schema` modules requires a local postgres instance with a
database named `unifi` in order to generate a jOOQ schema. This step can be
skipped with `mvn -pl '!unifi-core-schema' ...` if `unifi-core-schema` is
already installed.
