export const ZONE_LIST_FETCH = 'unifi.ZONE_LIST_FETCH'
export const ZONE_ENTITIES_SUBSCRIBE = 'unifi.ZONE_ENTITIES_SUBSCRIBE'
export const ZONE_ENTITIES_CLEAR_INACTIVE = 'unifi.ZONE_ENTITIES_CLEAR_INACTIVE'
