= unifi.id Core API Specification

JSON or MessagePack (TBD) over a WebSocket.

Most "short" identifier fields, e.g. username, email, clientReference, can be up to 64 characters long and are case-preserving unless specified otherwise. A character is a Unicode code point as per the PostgreSQL definition, and no (de)normalization takes place.

clientId and username have to match `^[a-zA-Z0-9._-]{1,64}$`.

JSON representation of non-native types:

- Timestamp: "yyyy-mm-ddThh:mm:ssX", where X is zone offset or 'Z'
- Byte sequence: Base-64 encoded string (MIME or URL-safe variants accepted)

Request format:

----
{
    "protocolVersion": "1.0.0",
    "releaseVersion": "1.0.0",
    "correlationId": <byte-sequence>,
    "messageType": "<module>.<service>.<operation>",
    "payload": {
        "param1": "value1",
        "param2": 2.0,
        "anotherParam": null
    }
}
----

Response format:

----
{
    "protocolVersion": "1.0.0",
    "releaseVersion": "1.0.0",
    "correlationId": <byte-sequence>,
    "messageType": "<module>.<service>.<operation>-result",
    "payload": ...
}
----

== Subscriptions

In addition to single request-response interactions, multiple responses are sent for some requests.

These have types matching `*.*.subscribe-*` by convention.

The flow is as follows:

- The client sends a request.
- The server sends zero or more non-error responses.
- If the server responds with an error (`core.error.*`) the subscription is terminated, i.e. no need for the client to unsubscribe.
- The client can unsubscribe by requesting `core.protocol.unsubscribe` with the same correlation ID. Some responses may still arrive after that.

Subscriptions are dropped on disconnection, so clients need to resubscribe after reconnection if appropriate.

== List/get options

Some `*.*.list-*` and `*.*.get-*` message types support the following functionality:

=== Filter (list only)

To restrict the set of results with equality conditions include the `"filter"` name in the payload object containing an object, whose names are item properties, and values are the values to restrict these properties to, e.g.:

----
"payload": {
    ...,
    "filter": {
        "active": true,
        ...
    }
}
----

=== With

To specify what associated data to include include the `"with"` name in the payload object containing an array of entity types to include, e.g.:

----
"payload": {
    ...,
    "with": ["detectable", "image", ...]
}
----

== Editing

A request to edit a resource generally takes the following form:

----
"payload": {
    ...clientId and other ID fields...,
    "changes": {
        "name": "My New Name",
        "active": false,
        "image": null, /* optional fields can be reset like this */
        /* missing "email" key means it won't be changed */
    }
}
----

TODO: Update API spec below. Out of sync with reality!

== Clients

=== List clients

- Message type: core.client.list-clients
- Request params: <none>
- Response params: (sequence of)
* clientId: string
* displayName: string
* logo: byte sequence

== Operators

=== Register operator

Register a new operator, optionally invite by email.
Invitation tokens and password reset tokens are identical.

- Message type: core.operator.register-operator
- Request params:
* clientId: string
* username: string
* name: string
* email: string
* invite: boolean (invite to set login password?; can also be done later)
- Response params: <none>

=== Authenticate with a password

- Message type: core.operator.auth-password
- Request params:
* clientId: string
* username: string
* password: string
- Response params:
* token: byte sequence
* expiryDate: timestamp

=== Authenticate with a token

- Message type: core.operator.auth-token
- Request params:
* token: string
- Response params:
* expiryDate: timestamp

=== Invalidate current token

- Message type: core.operator.invalidate-auth-token
- Request params: <none>
- Response params: <none>

=== List operators

- Message type: core.operator.list-operators
- Request params:
* clientId: string
- Response params: (sequence of)
* clientId: string
* name: string
* username: string
* email: string
* active: boolean

=== Get operator

- Message type: core.operator.get-operator
- Request params:
* clientId: string
* username: string
- Response params:
* clientId: string
* username: string
* name: string
* email: string
* active: boolean

=== Invite operator to set password

- Message type: core.operator.invite-operator
- Request params:
* clientId: string
* username: string
- Response params: <none>

=== Request password reset

- Message type: core.operator.request-password-reset
- Request params:
* clientId: string
* username: string
- Response params: <none>

=== Get password reset info

- Message type: core.operator.get-password-reset
- Request params:
* clientId: string
* username: string
* token: byte sequence
- Response params: (null if invalid)
* expiryDate: timestamp
* operator: { clientId: string, username: string, name: string, email: string }

=== Set password

Set a password using a valid password reset token.

- Message type: core.operator.set-password
- Request params:
* clientId: string
* username: string
* token: byte sequence
- Response params: <none>


=== Change password

- Message type: core.operator.change-password
- Request params:
* currentPassword: string
* password: string
- Response params: <none>

== Errors

- core.error.already-exists
- core.error.authentication-failed
- core.error.internal-server-error
- core.error.invalid-parameter-format
- core.error.missing-parameter
- core.error.not-found
- core.error.unauthorized
- core.error.unknown-message-type
- core.error.validation-failure
