ALTER TABLE core.client
  ALTER register_time TYPE TIMESTAMP WITH TIME ZONE USING register_time AT TIME ZONE 'UTC';

ALTER TABLE core.operator
  ALTER since TYPE TIMESTAMP WITH TIME ZONE USING since AT TIME ZONE 'UTC';

ALTER TABLE core.operator_login_attempt
  ALTER attempt_time TYPE TIMESTAMP WITH TIME ZONE USING attempt_time AT TIME ZONE 'UTC';

ALTER TABLE core.operator_password
  ALTER since TYPE TIMESTAMP WITH TIME ZONE USING since AT TIME ZONE 'UTC';

ALTER TABLE core.operator_password_reset
  ALTER since TYPE TIMESTAMP WITH TIME ZONE USING since AT TIME ZONE 'UTC';

ALTER TABLE core.operator_password_reset_history
  ALTER since TYPE TIMESTAMP WITH TIME ZONE USING since AT TIME ZONE 'UTC';

ALTER TABLE core.agent_password
  ALTER since TYPE TIMESTAMP WITH TIME ZONE USING since AT TIME ZONE 'UTC';

ALTER TABLE core.assignment
  ALTER since TYPE TIMESTAMP WITH TIME ZONE USING since AT TIME ZONE 'UTC';

ALTER TABLE core.rfid_detection
  ALTER detection_time TYPE TIMESTAMP WITH TIME ZONE USING detection_time AT TIME ZONE 'UTC';

ALTER TABLE core.client_config
  ALTER since TYPE TIMESTAMP WITH TIME ZONE USING since AT TIME ZONE 'UTC';

ALTER TABLE core.visit
  ALTER start_time TYPE TIMESTAMP WITH TIME ZONE USING start_time AT TIME ZONE 'UTC',
  ALTER end_time TYPE TIMESTAMP WITH TIME ZONE USING end_time AT TIME ZONE 'UTC';

ALTER TABLE core.permission
  ALTER since TYPE TIMESTAMP WITH TIME ZONE USING since AT TIME ZONE 'UTC';

ALTER TABLE core.permission_history
  ALTER since TYPE TIMESTAMP WITH TIME ZONE USING since AT TIME ZONE 'UTC',
  ALTER until TYPE TIMESTAMP WITH TIME ZONE USING until AT TIME ZONE 'UTC';
