export const LIST_SCHEDULE_STATS = 'unifi.LIST_SCHEDULE_STATS';
export const LIST_BLOCKS = 'unifi.LIST_BLOCKS';
export const GET_CONTACT_ATTENDANCE_FOR_SCHEDULE = 'unifi.GET_CONTACT_ATTENDANCE_FOR_SCHEDULE';
