export const HOLDERS_LIST_FETCH = 'unifi.HOLDERS_LIST_FETCH'
export const HOLDER_GET_FETCH = 'unifi.HOLDER_GET_FETCH'
export const HOLDER_ADD = 'unifi.HOLDER_ADD'
export const HOLDER_UPDATE = 'unifi.HOLDER_UPDATE'
export const PROGRAMMES_LIST_FETCH = 'unifi.PROGRAMMES_LIST_FETCH'
