= Infrastructure

== Agent deployment

. Take a clean box with at least 8GB of RAM.
. Install Debian 9 selecting only "standard system utilities" and "SSH server".
. Run the following commands as root, replacing `192.168.2.248` with the IP address of the agent machine:
+
----
cd /root
wget https://github.com/megawarne-consulting/unifi.id/archive/master.zip
unzip unifi-id-master.zip

wget -qO- https://cfengine-package-repos.s3.amazonaws.com/pub/gpg.key | apt-key add -
echo "deb https://cfengine-package-repos.s3.amazonaws.com/pub/apt/packages stable main" > /etc/apt/sources.list.d/cfengine-community.list
apt-get install apt-transport-https
apt-get update
apt-get install cfengine-community
# sync CF Engine content before bootstrapping
sudo rsync -vrlpxE /root/unifi-id-master/infrastructure/deployment/masterfiles/* /var/cfengine/masterfiles/
/var/cfengine/bin/cf-agent --bootstrap 192.168.2.248
cd /var/cfengine/inputs
# Run the cf-agent, running the unifi.id agent policies
cf-agent -Kf failsafe.cf && cf-agent -v -D unifi_role_agent -Kf promises.cf
----
+
. Repeat the commands on the last line until the reported fulfilled promises add up to 100.0%.
. Configure agent in `/etc/unifi/unifi-core-agent.conf`, e.g.:
+
----
UNIFI_CLIENT_ID=insert-client-id-here
UNIFI_AGENT_ID=insert-agent-id-here
UNIFI_SERVICE_URI=wss://app.unifi.id/agents/msgpack
UNIFI_AGENT_PASSWORD=abcd
----
+
. Restart agent.
systemctl restart unifi-core-agent

. Check for error/syslog via
journalctl -f -u unifi-core-agent

== Certificate renewal

The public and agent APIs, and the web app require an X.509 certificate (aka SSL certificate) for their operation. This
certificate is obtained from Let's Encrypt, is valid for three months and must be renewed before its expiry date to
avoid "Invalid certificate" errors. The process for obtaining a certificate (whether new, renewed or already expired) is
as follows:

. SSH into production service EC2 instance (admin@app.unifi.id) and log into your DNS provider account.
. Run on the EC2 instance: `sudo /opt/bin/unifi-get-cert`
. Follow the instructions, entering an email address for renewal reminders, adding the displayed `_acme-challenge.app`
  TXT records in DNS Made Easy and removing all the old ones (there'll be one or two).
. Once the verification succeeds run: `sudo systemctl reload nginx`
. Open https://centralworking.app.unifi.id and https://app.unifi.id in Chrome (Not Found error is OK for the latter) and
  check certificate validity and expiry for both sites by clicking on the padlock in the address bar. Expiry time should
  be three months in the future.
. Use Developer Tools (View > Developer) Security tab for more debugging information if necessary.

Read the CA documentation at https://letsencrypt.org/docs/ for information on expiry, revocation, etc.
